// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZdwBr4dBhOm29nx4g9LXT_Qjqxdx0Qrs',
    appId: '1:250348373756:web:91e90b4107735fb5417979',
    messagingSenderId: '250348373756',
    projectId: 'qrcode-flutter-bd2af',
    authDomain: 'qrcode-flutter-bd2af.firebaseapp.com',
    storageBucket: 'qrcode-flutter-bd2af.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5F0ZvTMGPbG9Hucxcf2DqkG70-Id3y9w',
    appId: '1:250348373756:android:f38b8c635639d351417979',
    messagingSenderId: '250348373756',
    projectId: 'qrcode-flutter-bd2af',
    storageBucket: 'qrcode-flutter-bd2af.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpOggsJ15fV6_Q_MuK1wgYb8d8qvT5fGA',
    appId: '1:250348373756:ios:89d2dad82d87d02d417979',
    messagingSenderId: '250348373756',
    projectId: 'qrcode-flutter-bd2af',
    storageBucket: 'qrcode-flutter-bd2af.appspot.com',
    iosBundleId: 'com.example.qrcodeFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpOggsJ15fV6_Q_MuK1wgYb8d8qvT5fGA',
    appId: '1:250348373756:ios:fb45d9d2b6b1eab1417979',
    messagingSenderId: '250348373756',
    projectId: 'qrcode-flutter-bd2af',
    storageBucket: 'qrcode-flutter-bd2af.appspot.com',
    iosBundleId: 'com.example.qrcodeFlutter.RunnerTests',
  );
}
